### ISSUE TITLE
Example code mismatch in readme

### ISSUE THREAD

**Issue by gmbuell** [adhocteam/pushup#70]
The example code shown in the png at the top of the readme (coming from file example-syntax-highlighting.png) shows different syntax than the example code under the "Pages in Pushup" section. Namely, "Pages in Pushup" code has "^else" while the image is missing the ^ before the else. Which is correct? Does either work?

**Comment by llimllib** [comment]
Good catch, the screenshot is wrong and `else` ought to be `^else`
