### ISSUE TITLE
suggestion：support utility-first CSS framework

### ISSUE THREAD

**Issue by chenghonour** [adhocteam/pushup#87]
Such as Tailwind CSS

**Comment by paulsmith** [comment]
Currently Pushup is agnostic as to what CSS libraries and frameworks users bring to it. I would be hesitant to bless a particular CSS framework and bundle it or provide syntax or library support for it, without first understanding more the potential need and the tradeoffs.

**Comment by chenghonour** [comment]
> Currently Pushup is agnostic as to what CSS libraries and frameworks users bring to it. I would be hesitant to bless a particular CSS framework and bundle it or provide syntax or library support for it, without first understanding more the potential need and the tradeoffs.

Providing framework support like Tailwind CSS makes it easier for developers to design pages, because CSS is the key to web pages. Or there is a more convenient way to write CSS, which is important for pushup.
